services:
  pkcs11-lab: &pkcs11-lab
    build:
      context: .
      dockerfile: Dockerfile
      target: pkcs11-java
    user: "${PKCS11_LAB_USER:-course}"
    group_add:
      - softhsm
    volumes:
      - ..:/workspace
    working_dir: /workspace
    tty: true
    stdin_open: true

  pkcs11-go:
    <<: *pkcs11-lab
    build:
      context: .
      dockerfile: Dockerfile
      target: pkcs11-go

  pkcs11-kotlin:
    <<: *pkcs11-lab
    build:
      context: .
      dockerfile: Dockerfile
      target: pkcs11-kotlin

  pkcs11-csharp:
    <<: *pkcs11-lab
    build:
      context: .
      dockerfile: Dockerfile
      target: pkcs11-csharp

  pkcs11-dev:
    <<: *pkcs11-lab
    build:
      context: .
      dockerfile: Dockerfile
      target: pkcs11-dev
